version: "3.8"
services:
    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - backend
    db:
        image: postgres:14.4
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis:7.0.4
        restart: unless-stopped
        tty: true
        ports:
            - "${REDIS_PORT:-6379}:6379"
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
    node:
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        tty: true
        restart: always
        ports:
            - "${FRONT_PORT:-5173}:5173"
        working_dir: /var/www
        volumes:
            - .:/var/www
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
volumes:
    pgdata:
        driver: local
    cache:
        driver: local
    node_modules:
        driver: local
